
import type { Contract, Partida, Certificate, PackageItem, CertificateType, Container } from '../types';
import { getHarvestYear } from './companyData';

// Helper to estimate tare weight based on package type string
const estimateTare = (packageType: string): number => {
    const type = packageType.toLowerCase();
    if (type.includes('jute') || type.includes('yute')) {
        if (type.includes('grainpro')) return 1.2; // Jute + GP
        return 1.0; // Just Jute
    }
    if (type.includes('big bag')) return 4.0;
    if (type.includes('jumbo')) return 5.0;
    if (type.includes('box') || type.includes('caja')) return 2.0;
    return 0;
};

export const mapPartidaToCertificate = (
    contract: Contract, 
    partida: Partida, 
    type: CertificateType, 
    activeCompany: 'dizano' | 'proben'
): Partial<Certificate> => {
    
    const unitWeightNum = Number(partida.numBultos) > 0 ? Number(partida.pesoKg) / Number(partida.numBultos) : 0;
    const tare = estimateTare(partida.packageType);

    const commonPackages: PackageItem[] = [{
        id: new Date().toISOString(),
        type: partida.packageType === 'Otro' ? (partida.customPackageType || '') : partida.packageType,
        quantity: partida.numBultos,
        unitWeight: unitWeightNum > 0 ? Number(unitWeightNum.toFixed(2)) : '',
        tareUnitWeight: tare,
        grossUnitWeight: unitWeightNum > 0 ? Number((unitWeightNum + tare).toFixed(2)) : '',
        marks: partida.marks || '',
        quality: contract.coffeeType || '',
        contains: 'CAFE ORO'
    }];

    const commonContainers: Container[] = [{
        id: new Date().toISOString(),
        containerNo: partida.containerNo || '',
        sealNo: partida.sealNo || '',
        packages: commonPackages
    }];

    const baseData: Partial<Certificate> = {
        company: activeCompany,
        type: type,
        certificateDate: new Date().toISOString().split('T')[0],
        consignee: contract.buyer || '',
        notify: contract.buyer || '', // Default notify to buyer
        destination: partida.destino || '',
        product: `${contract.coffeeType || 'GREEN COFFEE'}, CROP ${contract.harvestYear || getHarvestYear(contract.saleDate || '')}`.toUpperCase(),
        shippingLine: partida.naviera === 'Otro' ? partida.customNaviera : partida.naviera,
        billOfLadingNo: '', // No field in Partida for BL Number explicitly yet, but kept structure
        containers: commonContainers,
        exporterName: activeCompany === 'dizano' ? 'Yony Roquel' : 'Export Manager', // Placeholder
        contractNo: contract.contractNumber,
    };

    if (type === 'porte') {
        return {
            ...baseData,
            place: 'Guatemala',
            consignee: partida.destino || contract.buyer, // Porte usually consigned to destination warehouse/port
            transportCompany: '', // Manual fill
            driverName: '', // Manual fill
            transportUnit: '', // Manual fill
            licensePlate: '', // Manual fill
            observations: `PARTIDA: ${partida.partidaNo}\nBOOKING: ${partida.booking || 'N/A'}`,
            totalNetWeight: Number(partida.pesoKg),
            totalGrossWeight: Number(partida.pesoKg) + (Number(partida.numBultos) * estimateTare(partida.packageType)),
        };
    }

    if (type === 'invoice') {
        // For Invoice, we structure packages differently usually (by Line Item)
        // But mapping to the same PackageItem structure for the form
        const invoicePackages: PackageItem[] = [{
            id: new Date().toISOString(),
            quantity: Number(partida.pesoKg) / 46, // Quantity in QQS usually for invoice? Or LBS? Defaulting to QQs based on 'quintales' field context
            type: 'QQS', // Unit
            description: `${contract.coffeeType}\nMARCAS: ${partida.marks || 'N/A'}`,
            unitValue: partida.finalPrice, // Price per unit
            partidaNo: partida.partidaNo,
            unitWeight: 46, // 1 qq = 46kg
            marks: ''
        }];

        return {
            ...baseData,
            customerName: contract.buyer,
            consignee: '', // Address usually
            shippedVia: 'Marítimo',
            terms: 'FOB',
            packages: invoicePackages,
            invoiceNo: '', // Auto-generated by form logic usually
        };
    }

    if (type === 'packing' || type === 'weight' || type === 'quality') {
        return {
            ...baseData,
            shipmentDate: partida.etd || baseData.certificateDate,
            packingPlace: 'Beneficio Las Américas', // Default or empty
            totalNetWeight: Number(partida.pesoKg),
            totalGrossWeight: Number(partida.pesoKg) + (Number(partida.numBultos) * estimateTare(partida.packageType)),
        };
    }

    return baseData;
};
